### ISSUE TITLE
Several concerned questions

### ISSUE THREAD

**Issue by JFOC** [troychaplin79/wp-multitenant#3]
Hi,
I have several question:

1. each tenant has different database with other? or same database?
2. How is the backup process from the tenant side? anyone making a backup on any of the sites would also end up backing up the entire WordPress instance (which happens to have many other sites)?
3. each tenant could have custom domain and ssl ?
4. when using a file manager plugin, is a tenant able to access other tenant directories and files?

**Comment by Bfrank-Epik** [comment]
1.  Since each site has it's own wp-config.php that is not a symlink, each site can have a distinct database.  

You would need to create a database for each site that you want to deploy, then update that sites wp-config.php with the credentials and location of the database server.

![image](https://user-images.githubusercontent.com/64999837/137649149-720dac7a-7db2-4d19-abea-e808d4cfcfa7.png)

2.  A backup from within a WordPress instance backup would only grab that instance, and the database defined in wp-config.php.  
Something to note however, since the core WordPress files are symlinks I am not sure how they would be backed up and restored.  If the backup captures only the symlinks then a restore would need to happen on a wp-multitenant server with the same directory structure as the previous server.

3.  Yes, but you would need to configure that at the http server.   In Apache, you would create a new Vhost to serve up the new unique domain/ssl.

4.  This question is too broad to answer here as not all plugins are created equal.  I would suggest that you setup a test environment with a couple of domains, install the plugins that you would like to use, then verify that they work as per your requirements.

**Comment by troychaplin** [comment]
Apologies @JFOC I didn't realize I had a couple issues on the repo... And big thanks to @Bfrank-Epik for providing some solid answers!
